### ISSUE TITLE
wrong syntax highlighted for c code block.

### ISSUE THREAD

**Issue by iDragonfly2050** [atom/language-gfm#207] opened 2017-05-21 05:20 UTC
### Prerequisites

-   [x] Put an X between the brackets on this line if you have done all of the following:
    -   Reproduced the problem in Safe Mode: <http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    -   Followed all applicable steps in the debugging guide: <http://flight-manual.atom.io/hacking-atom/sections/debugging/>
    -   Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    -   Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    -   Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

wrong syntax highlighted for c code block.

### Steps to Reproduce

1.  input c code block:

```cpp
#include <cstdio>

int main() {
    int a[3][3];
    printf("a = %p\n", a);
    printf("&a = %p\n", &a);
    printf("*a = %p\n", *a);
    printf("a[0] = %p\n", a[0]);
    printf("&a[0] = %p\n", &a[0]);
    printf("&a[0][0] = %p\n", &a[0][0]);
    return 0;
}
```

**Expected behavior:**
![tim 20170521131342](https://cloud.githubusercontent.com/assets/16486215/26281392/f79ef9c6-3e27-11e7-8f31-4c6117d4a7ee.png)

**Actual behavior:**
![tim 20170521131328](https://cloud.githubusercontent.com/assets/16486215/26281391/f76a4690-3e27-11e7-9838-4032cf326090.png)

**Reproduces how often:** Always.

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
language-gfm : 0.88.1

**Comment by 50Wliu** [comment] 2017-05-22 21:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-c#146. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-22 21:56 UTC
