### ISSUE TITLE
Markdown Syntax Highlighting processes underscores in a code block

### ISSUE THREAD

**Issue by izuzak** [atom/language-gfm#39] opened 2014-08-01 09:02 UTC
_(Originally reported in https://github.com/atom/atom/issues/3145 by @5an1ty)_

> As an example use this code as markdown:

	This is a test

		_.bindAll(this,'test');

	this is the end of the test

> This will render two lines as pink because the parser does not notice the _ is in a code block

> ![screen shot 2014-07-31 at 23 36 27](https://cloud.githubusercontent.com/assets/5538404/3772023/ed3e4a90-18fa-11e4-83af-10195b9a7d1a.png)

**Comment by 50Wliu** [comment] 2015-01-16 01:09
This also seems like a duplicate of #44, but this one was opened first, so which one is the real duplicate? :wink:

**Comment by kevinsawicki** [comment] 2015-01-16 01:11
Yeah, I think closing this one makes sense, #44 has a bit more details wise.

**Closed by kevinsawicki** 2015-01-16 01:11 UTC
Labels: bug
