### ISSUE TITLE
Syntax highlight doesn't mark bold properly after/before alnum characters

### ISSUE THREAD

**Issue by jaeyeom** [atom/language-gfm#138] opened 2016-02-11 07:53 UTC
Markdown syntax highlight doesn't mark bold properly if the bold area starts after alpha-numeric characters and/or ends before alpha-numeric characters.

## Repro Steps

1. Open a markdown file.
2. Try put `**bb**cc` or `aa**bb**`

**Expected:** Only **bb** should be bolded.
**Actual:** The bold area doesn't end or doesn't start.

This is very painful for CJK languages whose words are not always spaced.

## Command History

```
     -0:09.9 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -0:08.8 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:02.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.is-focused)
```

## Versions

* **Atom:**       1.5.1
* **Atom-Shell:**
* **OS:**         Microsoft Windows 10 Home
* **Misc**
    * apm  1.6.0
    * npm  2.13.3
    * node 0.10.40
    * python 3.5.1
    * git 2.7.1.windows.1
    * visual studio

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by lee-dohm** [comment] 2016-02-11 21:57
This is a duplicate of https://github.com/atom/language-gfm/issues/117 with an additional test case. The root cause though is asterisks in the middle of "words". You may want to subscribe there for updates.

Thanks for reporting!

**Closed by lee-dohm** 2016-02-11 21:57 UTC

**Comment by jaeyeom** [comment] 2016-02-11 22:44
Thanks. I missed the duplicate issue. This is important issue for CJK users, because there are no spaces in Chinese and Japanese, and spaces are mostly but not always a word break in Korean.
