### ISSUE TITLE
Syntax highlighting errors when letter **B**olding

### ISSUE THREAD

**Issue by boazsegev** [atom/language-gfm#203] opened 2017-05-04 01:31 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting will break when using bold (\*\*) in the middle of a word, i.e. \*\*B\*\*old becomes an endless **Bold (...)** instead of **B**old.

### Steps to Reproduce

1. Open markdown document.
2. Write: \*\*B\*\*olding is caused by having time as your barber.

**Expected behavior:**

Syntax highlighting should show: **B**olding is caused by having time as your barber.

**Actual behavior:** 

Syntax highlighting should show: **Bolding is caused by having time as your barber.**

**Reproduces how often:**

Always (sadly, even inside code blocks, but this might be a different issue).

### Versions

OSX 10.12.4
Atom.io 1.16.0
language-gfm 0.88.1

**Comment by rsese** [comment] 2017-05-06 04:50
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/117. You may want to subscribe there for updates.  

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-06 04:50 UTC

**Comment by boazsegev** [comment] 2017-05-06 05:12
I'm Apologize. I didn't notice that report when I searched for duplicates (and it's the first search item... I don't know how I missed it!)... My bad.

I'll follow the issue over there.

Thanks for your time and your patience.

**Comment by rsese** [comment] 2017-05-09 05:46
No problem, we appreciate that you looked for existing issues :v:
