### ISSUE TITLE
The tab key no longer work

### ISSUE THREAD

**Issue by samegek** [atom/language-gfm#156] opened 2016-06-05 05:08 UTC
when i edit like .md file by pressing the tab key,nothing happed.No spaces,no tab.if i edit not like  .md  file,everything will be okay.

**Comment by lee-dohm** [comment] 2016-06-05 06:22
Can you give us steps to reproduce the problem? I can't reproduce this using Atom v1.9.0-dev-6991246 on Mac OS X 10.11.5. Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Ben3eeE** [comment] 2016-12-19 11:44
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-gfm/issues/156#issuecomment-223795653. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-19 11:44 UTC
Labels: more-information-needed
