### ISSUE TITLE
Wrong syntax highlighted for cpp code block

### ISSUE THREAD

**Issue by iDragonfly2050** [atom/language-gfm#206] opened 2017-05-21 05:08 UTC
### Prerequisites

-   [x] Put an X between the brackets on this line if you have done all of the following:
    -   Reproduced the problem in Safe Mode: <http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    -   Followed all applicable steps in the debugging guide: <http://flight-manual.atom.io/hacking-atom/sections/debugging/>
    -   Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    -   Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    -   Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

wrong syntax highlighted for cpp code block.

### Steps to Reproduce

1.  input cpp code block:

```cpp
class A {
public:
    void fun(int a, int b, int c) {
        std::cout << "A::fun()" << std::endl;
        std::cout << a << std::endl;
        std::cout << b << std::endl;
        std::cout << c << std::endl;
    }
};


int main() {
    A a;
    using namespace std::placeholders;
    std::function<void(int)> f1 = std::bind(&A::fun, a, _1, 99, 99);
    std::function<void(int)> f2 = std::bind(&A::fun, a, 99, _1, 99);
    std::function<void(int)> f3 = std::bind(&A::fun, a, 99, 99, _1);
    std::function<void(int, int)> f4 = std::bind(&A::fun, a, 99, _1, _2);

    f1(1);
    f2(1);
    f3(1);
    f4(1, 2);
    return system("pause");
}
```

**Expected behavior:** ![right behavior](https://cloud.githubusercontent.com/assets/16486215/26281313/0fc83cbc-3e26-11e7-8c58-5aed1a2c8992.png)

**Actual behavior:**![wrong behavior](https://cloud.githubusercontent.com/assets/16486215/26281312/0fc7a374-3e26-11e7-9d11-0929aa612ed1.png)

**Reproduces how often:** Always.

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
language-gfm  : 0.88.1

**Comment by 50Wliu** [comment] 2017-05-22 21:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-c#146. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-22 21:56 UTC

**Comment by iDragonfly2050** [comment] 2017-05-23 04:31
@50Wliu 
Are you sure this bug belong to [atom/language-c#146](https://github.com/atom/language-c/issues/146)? Because when i press "ctrl + shift + l",  and selected "c++", it seem like work correctly.

**Comment by 50Wliu** [comment] 2017-05-23 04:44
Yep.  It's a tricky bug.  language-c uses the special `$base` syntax, which basically means "inherit all the grammars from the base grammar, not just this one".  That's meant for C++, which uses a lot of patterns from C.  Without `$base`, the patterns that are inherited from C only get C highlighting and not C++ highlighting.  However, this falls apart when embedding C/C++ in GFM, because now `$base` points to...the GFM grammar.
