### ISSUE TITLE
Wrongly parsed code blocks as markdown

### ISSUE THREAD

**Issue by AlynxZhou** [atom/language-gfm#233] opened 2018-09-28 05:19 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you have a code block in your markdown file, and the code has chars like `*`, it will be process as a part of markdown, however, I think code blocks are just code and you shouldn't process `*` in code as italic, I just want to define a pointer in C...

![screenshot from 2018-09-28 13-11-59](https://user-images.githubusercontent.com/8444615/46189339-c5d15400-c320-11e8-9bc9-6639db791ae3.png)

### Steps to Reproduce

1. Create a markdown file.
2. Create a code block with `c` because we are going to write C code.
3. Insert some code like `int *ptr = NULL;` and see code after `*` becomes italic and breaks highlighting.

**Reproduces how often:** Every time.

### Versions

```
Atom    : 1.30.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm  2.1.2
npm  6.4.1
node 10.11.0 x64
atom 1.30.0
python 2.7.15
git 2.19.0
```

**Comment by rsese** [comment] 2018-09-28 20:31
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-gfm/issues/44 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-28 20:31 UTC
