### ISSUE TITLE
Should not recognize italic in code block.

### ISSUE THREAD

**Issue by arielyang** [atom/language-gfm#76] opened 2015-02-04 16:04 UTC
line 176, the code style is interrupted by the asterisk.

![screen shot 2015-02-04 at 23 25 22](https://cloud.githubusercontent.com/assets/212329/6043142/26497b6c-acc5-11e4-82da-fba1cd887159.png)

**Comment by arielyang** [comment] 2015-02-04 16:05
Sorry. line 176 is

- (BOOL)application:(UIApplication *) application didFinishLaunchingWithOptions:(NSDictionary *

**Comment by arielyang** [comment] 2015-02-04 16:05
Sorry. line 176 is

\- (BOOL)application:(UIApplication *) application didFinishLaunchingWithOptions:(NSDictionary *

**Comment by 50Wliu** [comment] 2015-02-04 16:42
Duplicate of #44.

**Closed by 50Wliu** 2015-02-04 16:42 UTC
