### ISSUE TITLE
Bug: Code highlighting in markdown does not stop after closing ticks (```)

### ISSUE THREAD

**Issue by pilarArr** [atom/language-gfm#215] opened 2017-10-09 14:52 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you define a language in the code block for syntax highlighting, if you don't close something in the code properly it continues to highlight code even after the closing ticks (```)

### Steps to Reproduce

1. Create a `test.md` file in atom
2. Try this text:

```
    This text here is normal

    Now we have a javascript code block with a non closed function
    ```javascript
    const hello = {
    ```
    This text still looks like it's code highlighted.
```

**Expected behavior:**  The second line shouldn't be highlighted as code syntax after the closing ticks even if the function inside the code block is not closed. The syntax highlighting should end when the code block ends regardless of the code inside.

**Actual behavior:** The code after the closure for a code block looks like it's syntax highlighted

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: macOS High Sierra 10.13

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-10-10 05:20
Thanks for taking the time to contribute!

After reading through it, I think this is a duplicate of https://github.com/atom/language-gfm/issues/21 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-10 05:20 UTC
