### ISSUE TITLE
Markdown with Javascript linting error.

### ISSUE THREAD

**Issue by reggi** [atom/language-gfm#121] opened 2015-08-16 17:55 UTC
Bringing in these issues from other projects: 

It seems that the linter is attempting to lint the whole document instead of just the \`\`\`js & \`\`\`javascript code blocks.

![aug 11 2015 16 01](https://cloud.githubusercontent.com/assets/296798/9209012/56575660-4042-11e5-83b3-ba8d53784ce8.gif)
![screen shot 2015-08-11 at 3 57 32 pm](https://cloud.githubusercontent.com/assets/296798/9209013/56584840-4042-11e5-9c0b-8a66c77a206e.png)

From @steelbrain

> ..this is a language-markdown issue, it should give something like source.embedded.js instead of source.js, like other languages do.

https://github.com/atom-community/linter/issues/777
https://github.com/AtomLinter/linter-shellcheck/issues/23

**Comment by steelbrain** [comment] 2015-08-16 17:57
I believe the problem to be in the scope it specifies, it shouldn't give `source.js` for a js embedded inside markdown, it should give something like `source.embedded.js`.

**Comment by soulchainer** [comment] 2015-09-26 12:29
I got this problem with linter-shellcheck linting my markdown files: like I start them with a header, it thinks it's a shell script and lints it and gives a bunch of linting errors.

I go to linter-shellcheck github and in issue [Linter runs against markdown files #23](https://github.com/AtomLinter/linter-shellcheck/issues/23), @steelbrain tells to go to [Markdown get linted](https://github.com/atom-community/linter/issues/777). And there, well, issue closed and [Markdown with Javascript linting error](https://github.com/atom/language-gfm/issues/121) reference from here. So, my markdown get's linted like it's shellscript when it isn't not and it doesn't have nothing to do with embeding code inside it (I removed all the code embedded and got the same warnings). I'm confussed. Should I file this issue here or where?
Is this a problem of this package, or should `linter-shellcheck` simply allow to specify what type of files you want it to check? IDK.

**Comment by steelbrain** [comment] 2015-09-26 19:19
@soulchainer If you look at this line in `linter-shellcheck` it clearly specifies `source.shell`, it does not specify `source.embedded.shell`. so Yeah, this language package is providing incorrect scopes.

**Comment by rugk** [comment] 2015-09-26 20:32
Also happens with PHP: See https://github.com/AtomLinter/linter-php/issues/65.

**Comment by burodepeper** [comment] 2015-09-27 06:44
As a quick fix, you could all try the [language-markdown](https://atom.io/packages/language-markdown) package. Besides this being a little self-promotion, we are (re-)doing the markdown package, and embedded fenced code blocks are on the todo list to receive a smarter implementation.

I've just copied the grammar from `language-gfm`, changed the scopes to be embedded, and pushed an update. Let me now if this at least fixes your problems.

A few notes:
- `language-markdown` still needs a lot of love, but it is usable.
- You'll have to select `Markdown` manually via <kbd>^ + shift + L</kbd> for the time being.
- The markdown scopes in our package differ a little from `language-gfm`, so syntax highlighting might not work as intended. Install [minimal-syntax](https://atom.io/packages/minimal-syntax) for debugging styles.

**Comment by soulchainer** [comment] 2015-09-30 09:40
@burodepeper Well, that works, thanks. Only issue (like noted) is that I lose syntax highlighting of markdown itself (but for code blocks it's preserved). Like I don't need syntax highlighting for markdown so much, I'm fine with it for now :). I was pretty annoyed with all these false issues the linter was warning.

**Comment by burodepeper** [comment] 2015-09-30 09:42
@soulchainer That is probably because your theme doesn't support the classes my package uses. That will change later on. Let me know if you run into any other issues.

**Comment by jmgore75** [comment] 2016-01-22 22:54
@steelbrain Is there an official policy that markdown embedded source should be called something like `source.embedded.*`? I can't find anything more definitive than your comment in atom-community/linter#777.  [burodepeper/language-markdown](https://github.com/burodepeper/language-markdown) is currently using `embedded.source.*`.

**Comment by steelbrain** [comment] 2016-01-22 23:01
@jmgore75 It really depends on package authors, most of the grammar packages including the core ones follow the pattern `source.js`, `source.php` and `source.x`. When the languages import definitions from each other their rules become `source.js.embedded.html`, so `source.embedded.html` makes the most sense as it follows `source.x` tradition.

I am not favoring `source.js.embedded` just because `language-markdown` has it. I was introduced to it after I had spoken about this, it just feels right for it to be this way IMO.

That being said, I really think that all the markdown packages should use the same scope, if they do not. Linter providers will either have to leave them out or specify their scopes specifically.

**Comment by Arcanemagus** [comment] 2016-01-22 23:10
As far as I know the scope concept comes from TextMate originally, and their (admittedly outdated) documentation says the most general form should come first ([here](http://blog.macromates.com/2005/introduction-to-scopes/)), which would lend credence to the `source.embedded.___` style, since the content is source code first, then embedded within other source code.

That being said, over [here](https://manual.macromates.com/en/scope_selectors) they have an example of `source.php.embedded.html`, so it seems _everyone_ is making this up as they go :confused:... Personally the `source.embedded.___` scheme "feels" right to me, and is what I first saw used, I can see how `embedded.source.____` could make some sense though.

No matter what, I think everyone can agree that `language-gfm` marking embedded languages as `source.____` is terrible.

**Comment by 50Wliu** [comment] 2016-01-22 23:18
@MaximSokolov I'd appreciate your thoughts on this.

I don't think `embedded` is a top-level scope (though we could always make it one...:grin:), so my vote also goes to `source.embedded`.

**Comment by jmgore75** [comment] 2016-01-22 23:56
I don't know anything about TextMate, but `embedded.source.___` or `source.___.embedded` is more natural to me since `source.___` remains intact.  Although it would be best if linting was compositional and could lint individual blocks that declare a scope of `source.___`, instead of the whole file.  Then there wouldn't be a need for all these extra scope names.  I assume there is some technical reason that is not done already.  

In any case, I just want linter to not blow up in my face every time I write a fenced code block, which is to say "any way but the way it's done now".  Should I change #137 to use to `source.embedded.___`?

**Comment by steelbrain** [comment] 2016-01-22 23:58
@jmgore75 Linter already uses the scopes under your current cursor instead of the entire file. The reason we want `source.embedded.x` instead of `source.x`, is that users don't want their markdown files linted with all the javascript, shell and python linters they have installed.

**Comment by Arcanemagus** [comment] 2016-01-23 00:05
The consensus seems to be for `source.embedded.____`, but if anyone knows of an "official" source that would be great.

@jmgore75 As for the reason linting embedded blocks isn't done already essentially boils down to matching the linter output line/column back to the embedded block of code.

(There are other issues that make it hard, but not impossible, such as linters that only support linting files on disk.)

**Comment by jmgore75** [comment] 2016-01-23 00:10
@steelbrain OK, that makes sense.  I can see how fussy linters complaining about my explanatory snippets could get old real fast.  But in that case, and the whole point is not to do anything with it, does it even matter what the scope is? Wouldn't a simple `source.embedded`, no `.___` be sufficient for all fenced blocks? 

In any case I'll update #137.

**Comment by jmgore75** [comment] 2016-01-23 01:40
OK, now using `source.embedded.___` and `text.embedded.___` throughout the grammars on #137.  Should be OK to merge.

**Comment by jokeyrhyme** [comment] 2016-01-23 03:38
How do language packs for other mixed languages deal with this? For example, JSX allows XML-ish chunks here and there, and PHP is frequently mixed with HTML as a templating solution.

**Comment by burodepeper** [comment] 2016-01-23 07:52
I'm all up for somewhat standardized scopes, but that's a bigger issue than just `embedded.source.*` which I use in `language-markdown`. As @50Wliu mentions, I believe @MaximSokolov started an issue somewhere addressing these issues. Can anyone link me there again?

**Comment by MaximSokolov** [comment] 2016-01-23 15:56
`source.embedded.__` looks ok to me. @burodepeper: atom/atom#8430

**Comment by 50Wliu** [comment] 2016-02-06 22:49
Should be fixed by #137.

**Closed by 50Wliu** 2016-02-06 22:49 UTC
