### ISSUE TITLE
Incorrect application of italic when setting target in <a> tag.

### ISSUE THREAD

**Issue by nycdotnet** [atom/language-gfm#118] opened 2015-07-29 13:43 UTC
In Atom, if an `<a>` tag is created in a Markdown document that has a target attribute set to "_blank", the remainder of the document is considered italic due to the underscore.

For example:

```
Not Italic.
<a href="https://youtu.be/Km0DpfX5ZxM" target="_blank" alt="TypeScript programming using grunt-ts"><img src="https://img.youtube.com/vi/Km0DpfX5ZxM/0.jpg" /></a>
This will be italic. (span .markup .italic .gfm)
```

The target attribute *does* appear to be on the [whitelist for GitHub-flavored Markdown](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L69) (and this isn't seemingly an issue on the GitHub web site, nor in the Markdown preview), so I think the underscore in the target attribute should be ignored when inside a quoted attribute value in an HTML tag, and the following text should not have the `italic` class applied.

Thanks!

**Comment by mnquintana** [comment] 2015-07-29 15:24
Looks like this is a duplicate of https://github.com/atom/language-gfm/issues/44 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-29 15:24 UTC
