### ISSUE TITLE
Newline in link text breaks text syntax highlighting

### ISSUE THREAD

**Issue by caleb531** [atom/language-gfm#162] opened 2016-07-08 17:11 UTC
Hi,

I use the atom/language-gfm package frequently to write READMEs and other version-controlled Markdown files. I often use the atom/autoflow package to cap each line at my *Preferred Line Length* (this allows my git diffs to isolate small changes in long paragraphs).

However, I've noticed that when I run *Autoflow: Reflow Selection* on my paragraphs, if a Markdown link gets wrapped, the syntax highlighting for the link breaks.

**Before:**

![without-newline](https://cloud.githubusercontent.com/assets/872474/16695254/86788a74-44f3-11e6-9f5a-ea1777444321.png)

**After:**

![with-newline](https://cloud.githubusercontent.com/assets/872474/16695257/8cbb6c8a-44f3-11e6-9eb6-1314a5a465c1.png)

What's even stranger is that other formatted text (like \* for italics and \*\* for bold) does not lose syntax highlighting when wrapped (as shown above). I've tried to sift through the grammar file to locate the cause of this issue (a missing `\n` or whatnot), but I haven't had any success in finding anything.

**Comment by 50Wliu** [comment] 2016-07-15 11:32
This is a duplicate of #37 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 11:32 UTC
