### ISSUE TITLE
An unpaired `'` (apostrophe) in a codeblock breaks highlighting for some highlighters

### ISSUE THREAD

**Issue by mstanleyjones** [atom/language-gfm#178] opened 2016-12-16 22:31 UTC
Consider something like this:

<img width="669" alt="screen shot 2016-12-16 at 2 29 35 pm" src="https://cloud.githubusercontent.com/assets/7674613/21280663/2cbfe004-c39c-11e6-8050-17d45b5a1312.png">

This is a little annoying and it's hard to know how to work around it. Sometimes the apostrophe is in a command's output, and I can't exactly change it.

I saw lots of similar issues, but none with the apostrophe itself.

**Comment by mstanleyjones** [comment] 2016-12-16 22:43
Actually looking at my example closer, it is broken for `none` too!

**Comment by lee-dohm** [comment] 2016-12-23 23:51
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/133. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2016-12-23 23:51 UTC
