### ISSUE TITLE
Syntax highlighting broke when the code is invalid

### ISSUE THREAD

**Issue by jefferyyuan** [atom/language-gfm#239] opened 2019-05-30 01:05 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting broke when the code is invalid

### Steps to Reproduce
Create a markdown document, add the following code block, and : the bash code is invalid.
- The problem still exist after remove the *
-- start of the demo: check the source for full code demo:
```bash
for f in *.tar; do
```
#### another title
-- end of the demo
<img width="422" alt="Screen Shot 2019-05-29 at 6 05 38 PM" src="https://user-images.githubusercontent.com/2187508/58601137-64a9a980-823c-11e9-9520-9cf4aa55378c.png">

**Expected behavior:** [What you expect to happen]
- "another title" should be correctly highglited as header
**Actual behavior:** [What actually happens]
- "another title" is gray

**Reproduces how often:** [What percentage of the time does it reproduce?]
- Always
### Versions
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment] 2019-05-30 04:04
Thanks for contributing!

I believe this is a duplicate of https://github.com/atom/language-gfm/issues/171 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-30 04:04 UTC
