### ISSUE TITLE
Bad syntax highlighting when character in word is wrapped in italic or bold tags

### ISSUE THREAD

**Issue by rm-code** [atom/language-gfm#217] opened 2017-11-06 22:59 UTC
### Description

<img width="1072" alt="bildschirmfoto 2017-11-06 um 23 34 05" src="https://user-images.githubusercontent.com/11627131/32468328-183b7dd4-c34e-11e7-8b54-741b58f34f76.png">

### Steps to Reproduce

Wrap a single character within a word in `_` or `*` and see how the syntax highlighting goes crazy.

**Expected behavior:**

Working syntax highlighting.

**Actual behavior:**

Broken syntax highlighting.

**Reproduces how often:**

Each time.

### Versions

macOS 10.13.1

```
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```

**Comment by rsese** [comment] 2017-11-08 00:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/117. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-08 00:54 UTC
