### ISSUE TITLE
Links with newlines lose highlight

### ISSUE THREAD

**Issue by Yajo** [atom/language-gfm#200] opened 2017-04-22 07:20 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

An image is worth 1000 words:

![captura de pantalla de 2017-04-22 09-18-58](https://cloud.githubusercontent.com/assets/973709/25302358/c3238efc-273c-11e7-815a-34bdddbed79b.png)

### Steps to Reproduce

1. Write that.

**Expected behavior:** Should be rendered as a link.

**Actual behavior:** Links with newlines in between do not render as such.

**Reproduces how often:** 100%

### Versions

```
➤ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

➤ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.9.3

➤ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

**Comment by 50Wliu** [comment] 2017-04-22 15:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #37. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-22 15:32 UTC
