### ISSUE TITLE
Bold or Italic syntax highlighting works incorrectly with CJK words.

### ISSUE THREAD

**Issue by HyunSeob** [atom/language-gfm#143] opened 2016-02-29 06:29 UTC
See the screen shot.

<img width="769" alt="2016-02-29 3 23 15" src="https://cloud.githubusercontent.com/assets/6940487/13387274/66936e4c-def8-11e5-8025-ccbf9cc0f10c.png">
**Incorrectly working with CJK words**

But, highlighting works correctly with white space (or just other characters that don't contain CJK characters.)

<img width="764" alt="2016-02-29 3 26 17" src="https://cloud.githubusercontent.com/assets/6940487/13387319/cf944060-def8-11e5-9519-e44596686616.png">
**Correctly working with white space**

I discovered this issue only in bold or italic. Maybe other syntaxes work correctly.

**Comment by 50Wliu** [comment] 2016-02-29 17:09
This is a duplicate of #117 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-29 17:09 UTC
