### ISSUE TITLE
_ causes issues

### ISSUE THREAD

**Issue by rugk** [atom/language-gfm#122] opened 2015-08-20 18:59 UTC
The markdown syntax highlighting seem to display this something bit broken - and that's Atoms own license file (line 414):
![atomlicense](https://cloud.githubusercontent.com/assets/11966684/9392165/5d068dc4-477b-11e5-97a5-9df6ba46053e.PNG)

UI Theme: Atom Dark
Syntax Theme: One Dark
But that does not seem to matter I've switched both and it was still the same.

Moved from: https://github.com/atom/atom/issues/8460

**Comment by izuzak** [comment] 2015-08-20 19:01
This is a duplicate of https://github.com/atom/language-gfm/issues/44. You can use either `*` or `_` in markdown to italicize. This is also mentioned in https://github.com/atom/language-gfm/issues/44#issuecomment-108195355

**Comment by rugk** [comment] 2015-08-20 19:02
Ups sorry didn't saw this comment:
> "even if only for the _ case at first. "

https://github.com/atom/language-gfm/issues/44#issuecomment-108195355

So you can close

**Closed by izuzak** 2015-08-20 19:01 UTC
