### ISSUE TITLE
Bug in URL matching pattern

### ISSUE THREAD

**Issue by kolis** [atom/language-gfm#132] opened 2015-11-26 14:01 UTC
The following url
```md
https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=vboxsf+inotify+docker+volume
```

gives the following editor highlighting
![screen shot 2015-11-26 at 14 55 20](https://cloud.githubusercontent.com/assets/770348/11424577/7d7c3cc8-944e-11e5-819d-c2e05667dbb9.png)

**Comment by lee-dohm** [comment] 2015-11-27 00:11
This is a duplicate of https://github.com/atom/language-hyperlink/issues/7. Please subscribe to that issue. Thanks for reporting!

**Closed by lee-dohm** 2015-11-27 00:11 UTC
Labels: bug
