### ISSUE TITLE
Underscore in quotes breaks syntax highlighting and is interpreted when it should not be

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [atom/language-gfm#230] opened 2018-05-18 08:45 UTC
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

### Description
When using *GitHub Markdown* for syntax highlighting an underscore is interpreted in a quote

### Steps to Reproduce

1. open new file
2. set syntax highlighting to *GitHub Markdown* on the bottom right
3. type `>quoted._notquoted`

**Expected behavior:**
Everything is highlighted as quote, the underscore has no effect inside a quote

**Actual behavior:**
`_notquoted` and everything after it (even after new lines) is highlighted in a different color

![screenshot_20180518_104000](https://user-images.githubusercontent.com/17473656/40225127-7ee5f3da-5a88-11e8-8bb8-292a219f65ac.png)

**Reproduces how often:** 100%

### Versions
```bash
$ atom --version
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```bash
$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

OS: KDE neon based on Ubuntu LTS 16.04

**Comment by PanCakeConnaisseur** [comment] 2018-05-18 12:04
I also tested Atom 1.27.0 on Windows 10 with the same result.

**Comment by rsese** [comment] 2018-05-18 17:38
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-gfm/issues/44 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-18 17:38 UTC
