### ISSUE TITLE
Underscores in HTML attributes parsed as markdown open/close italics.

### ISSUE THREAD

**Issue by davepeck** [atom/language-gfm#71] opened 2015-01-16 00:44 UTC
For example, try writing `<a target="_blank">Hello</a>` in a `markdown` file in the `atom` editor and notice how everything after the `_` is italicized.

![Example screen shot](https://cloud.githubusercontent.com/assets/53165/5769823/e393576a-9cd5-11e4-9266-8321ca0f3449.png)

**Comment by 50Wliu** [comment] 2015-01-16 01:06
Duplicate of #44.

**Closed by 50Wliu** 2015-01-16 01:06 UTC

**Comment by davepeck** [comment] 2015-01-16 01:07
Not sure how this is a duplicate of #44 but I don't know the code, so okay! :-)
