### ISSUE TITLE
Highlighting error in Github Markdown

### ISSUE THREAD

**Issue by mnquintana** [atom/language-gfm#103] opened 2015-05-18 17:26 UTC
_From @juh2 on May 18, 2015 17:11_

I am using Atom to write Markdown files for processing with Pandoc. Citations are done like this:
[@foo_bar_2013]

If the citation key contains a dot highlighting is garbled. See attached screenshot.

![bildschirmfoto vom 2015-05-18 19 04 40](https://cloud.githubusercontent.com/assets/1416069/7685843/9624e90e-fd91-11e4-97e4-fd111dc55981.png)

_Copied from original issue: atom/atom#6845_

**Comment by juh2** [comment] 2015-05-29 08:53
If I can done anything to make this error reproducible, let me know. The bug makes Atom unusable for me so I am ready to help in every possible way.

**Comment by juh2** [comment] 2015-05-31 06:59
You can reproduce it in a more generic way with this text:

    Lorem ipsum dolor sit amet.

        SRC = *.md
    
    Lorem ipsum dolor sit amet.

![bildschirmfoto vom 2015-05-31 08 53 19](https://cloud.githubusercontent.com/assets/1416069/7900946/81a38fae-0772-11e5-9a9b-6d8236d16650.png)

It is caused by the asteriks followed by any character. You get the same result with an underscore.

    Lorem ipsum dolor sit amet.

        SRC = _md
    
    Lorem ipsum dolor sit amet.

In my original post I thought that the error is caused by the period. But it seems that it is the combination of underscore and period.

**Comment by 50Wliu** [comment] 2015-05-31 14:57
Thanks for the clarification @juh2!  After looking at the initial image again, it looks like this is actually a duplicate of #44, so if you guys could please subscribe there for updates, that would be great :smile:.

**Closed by 50Wliu** 2015-05-31 14:57 UTC
Labels: needs-reproduction
