### ISSUE TITLE
Incosistent Markdown styling in Atom 1.10.0

### ISSUE THREAD

**Issue by gitkrax** [atom/language-gfm#167] opened 2016-09-06 07:40 UTC
Moved here from atom/atom#12609. Updated with a sample document.

### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom 1.10.0 inconsistently styles Markdown text. I noticed this behavior after upgrading to Atom 1.10.0. The problem is consistent between different themes, so it sounds like a problem in Atom and not in a specific theme.

### Steps to Reproduce

Sample text to reproduce:
https://gist.github.com/gitkrax/8680dd9c1e3b6c1e133e7ae8eae6bfc5

**Expected behavior:** Markdown to be styled consistently.

**Actual behavior:** The broken styling looks like this:

![sieppaa](https://cloud.githubusercontent.com/assets/5079912/18265350/ff8124cc-741d-11e6-89b6-a1d7cdccc5d1.PNG)

### Versions

`atom --version`:

Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

`apm --version`:

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 1.7.11.msysgit.1
visual studio

OS:

Windows 7 Service Pack 1

**Comment by Ben3eeE** [comment] 2016-09-06 10:03
This was strange but I managed to reproduce it or something somehow. The key for me was to enable soft wrap.

Here is what I did:
1. Open an Atom window in safe mode with the linked `test.md` file.
2. Enable soft wrap in `language-gfm` settings (Somehow changing it in editor settings no longer works and I had to go into language specific settings to change this).
3. Scroll to an area where there is syntax highlighting and then away from that area.
4. Resize the Atom window a little bit.
5. Scroll back to the syntax highlighted area and observe it is incorrect.
6. Resize the Atom window and syntax highlighting is correct again.

Given the comment (quoted below) from the original issue this might be what you have observed. You see it more often in the longer document cause you are more likely to scroll away from a highlighted area, or something I don't know, maybe you only see it in markdown because you open and close markdown preview causing resizing. Thoughts?
>I am unable to consistently reproduce the behavior. I have a longer Markdown-document where the styling is consistently broken, but the manner in which it is broken varies when I open a new instance of Atom. I could not reproduce the behavior with a shorter Markdown document, so I am not sure what the trigger is.

I also noticed similar behavior when splitting and closing the new pane.
I also noticed the same behavior when not using the classic theme in Windows.
I tried all steps without soft wrap and it works correctly.
Also similar behavior with breakage when closing panes being fixed by resizing the window was noted here: https://github.com/atom/tabs/issues/362#issuecomment-239097435
I guess the next step would be to test in other languages to see if it is a problem there also and not limited to `language-gfm`

### Mandatory gifs
![soft wrap highlight 2](https://cloud.githubusercontent.com/assets/1058982/18268990/871502de-7426-11e6-8dce-7d37e31b131a.gif)
![soft wrap split](https://cloud.githubusercontent.com/assets/1058982/18268989/8712b448-7426-11e6-814c-adf8b998e353.gif)

**Comment by thomasjo** [comment] 2016-09-06 10:16
Following @Ben3eeE's steps above, I was able to reproduce the weird behavior.

<img width="807" alt="soft-wrap-bug" src="https://cloud.githubusercontent.com/assets/3622/18270035/40482516-742b-11e6-907a-55655f07bbfd.png">

Definitely something really, really weird going on here. Seems like we might be calculating some buffer ranges incorrectly when they scroll off-screen, or something along those lines. I don't know enough about the `TextBuffer` class + friends, but I'm guessing the error might go that far down the rabbit's hole.

/cc @as-cii @nathansobo @atom/feedback

**Comment by thomasjo** [comment] 2016-09-06 10:17
Note that it looks like this might actually be a bug in core after all, but I'll leave the final verdict up to @as-cii and @nathansobo who have both worked extensively on these things.

**Comment by 50Wliu** [comment] 2016-09-06 14:39
I ran into this briefly while working on a LaTeX file.

**Comment by 50Wliu** [comment] 2016-09-06 17:35
Fixed by https://github.com/atom/atom/issues/12610.

**Closed by 50Wliu** 2016-09-06 17:35 UTC
Labels: atom, bug

**Comment by Ben3eeE** [comment] 2016-09-07 06:35
For me the red lines under the text when closing a split pane is still incorrect in Atom 1.10.1, the other issue seems to have been fixed.
Seems almost any action(Move the cursor with the arrow keys, click in the pane, resize the Atom window) corrects the issue so it is just some visual bug. I can try with Windows 10 later to completely rule out it being a classic mode issue.

**Comment by nathansobo** [comment] 2016-09-07 13:38
@Ben3eeE are the red lines you're talking about just spell check running against all that latin in your example text?

**Comment by Ben3eeE** [comment] 2016-09-07 13:45
Yes it is just region misspelling from spell check package:
![spellcheck](https://cloud.githubusercontent.com/assets/1058982/18305056/0283dc00-74e6-11e6-82f9-70e28581873d.png)

**Comment by nathansobo** [comment] 2016-09-07 14:01
@Ben3eeE I can't reproduce. Would be cool if you could mess with your themes, try safe mode etc and open another issue if you learn more. Definitely looks like something we don't want happening.

**Comment by Ben3eeE** [comment] 2016-09-07 14:08
Gif :point_up:  is in safe mode and pic :point_up: is outside of safe mode with another ui and syntax theme.
Note that you need to have `soft wrap` enabled for this issue to reproduce, without soft wrap it doesn't reproduce for me.

I will try out some things and file another issue. In the spell-check repository?

**Comment by nathansobo** [comment] 2016-09-07 14:26
@Ben3eeE it's actually probably a core issue with highlight decorations, which is the API spell check is using to render those underlines.
